version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: docker/frankenphp/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./app:/app
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile
    environment:
      - APP_ENV=local
      - PHP_MEMORY_LIMIT=512M
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql_data:
  redis_data:
